#!/bin/bash

# get-volume script returns the current volume status of your system in a
# format suitable for use in xmobar. I found this script on this page:
#   http://karuppuswamy.com/wordpress/2011/09/03/how-to-get-a-productive-desktop-based-on-xmonad-and-xmobar/
# 
# Original author unknown -- credited to "a nice guy online".  :-)
#

str=`amixer sget Master,0`
str1=${str#Simple*[}
v1=${str1%%]*]}
il=`expr index "$str1" [`
o="off"
mutel=''
if [ ${str1:$il:3} == $o ]; then mutel='M'; fi
s=${str1:0:1}
str2=${str1#${str1:0:1}*[}
str1=$str2
str2=${str1#${str1:0:1}*[}
ir=`expr index "$str2" [`
muter=''
if [ ${str2:0:3} = $o ]; then muter='[M]'; fi
v2=${str2%\]}
v=${v1}\ $muter
echo $v
